before_script:
  - |
    $(npm bin)/set-up-ssh --key "$encrypted_93302a4c01a9_key" \
                          --iv "$encrypted_93302a4c01a9_iv" \
                          --path-encrypted-key ".travis/GitHub.enc"

script:
  - git remote add GitHub git@github.com:$TRAVIS_REPO_SLUG.git
  - mkdir -p .status
  - mkdir -p .coverage
  - make

after_script:
  # Add tests status.
  - git checkout "$TRAVIS_COMMIT"
  - git checkout -b meta/tests/$TRAVIS_BRANCH
  - git add .status
  - git commit -m "$TRAVIS_COMMIT" --allow-empty
  - git push GitHub HEAD:refs/heads/meta/tests/$TRAVIS_BRANCH
  # Add coverage status.
  - git checkout "$TRAVIS_COMMIT"
  - git checkout -b meta/coverage/$TRAVIS_BRANCH
  - git add .coverage
  - git commit -m "$TRAVIS_COMMIT" --allow-empty
  - git push GitHub HEAD:refs/heads/meta/tests/$TRAVIS_BRANCH

# blocklist
branches:
  except:
  - meta/.*
