script:
  - make

after_script:
  # Add tests status.
  - git checkout "$TRAVIS_COMMIT"
  - git checkout -b meta/tests/$TRAVIS_BRANCH
  - git add .tests
  - git commit -m "$TRAVIS_COMMIT" --allow-empty
  - git push origin HEAD:refs/heads/meta/tests/$TRAVIS_BRANCH
  # Add coverage status.
  - git checkout "$TRAVIS_COMMIT"
  - git checkout -b meta/coverage/$TRAVIS_BRANCH
  - git add .coverage
  - git commit -m "$TRAVIS_COMMIT" --allow-empty
  - git push origin HEAD:refs/heads/meta/tests/$TRAVIS_BRANCH

# blocklist
branches:
  except:
  - meta/.*
